"""
Created by Angelo John Benedict Laus of SF231
Created on May 23, 2024
Stacks
"""

fruits = []
fruits.append('apple')
fruits.append('banana')
fruits.append('grapes')
fruits.append('kiwi')
fruits.append('pears')
fruits.append('cherry')
fruits.append('orange')
fruits.append('guava')
fruits.append('mango')
fruits.append('avocado')
print('\nFull stack:')
print(fruits)
fruits.pop()
fruits.pop()
fruits.pop()
fruits.pop()
fruits.pop()
fruits.pop()
print('\nPears removed:')
print(fruits)
fruits.append('apricot')
fruits.append('persimmon')
fruits.append('lime')
fruits.append('lychee')
print('\nAdded apricot, persimmon, lime, and lychee:')
print(fruits)
fruits.pop()
fruits.pop()
fruits.pop()
fruits.pop()
print('\nApricot removed:')
print(fruits)
fruits.append('watermelon')
fruits.append('pineapple')
print('\nAdded watermelon and pineapple:')
print(fruits)
fruits.pop()
fruits.pop()
fruits.pop()
fruits.pop()
fruits.pop()
fruits.pop()
print('\nTop element removed:')
print(fruits)